team_ids_one_on_one = {
        "Cardinals": 1,
        "Falcons": 2,
        "Ravens": 3,
        "Bills": 4,
        "Panthers": 5,
        "Bears": 6,
        "Bengals": 7,
        "Browns": 8,
        "Cowboys": 9,
        "Broncos": 10,
        "Lions": 11,
        "Packers": 12,
        "Texans": 13,
        "Colts": 14,
        "Jaguars": 15,
        "Chiefs": 16,
        "Chargers": 27,
        "Rams": 26,
        "Dolphins": 17,
        "Vikings": 18,
        "Patriots": 19,
        "Saints": 20,
        "Giants": 21,
        "Jets": 22,
        "Raiders": 23,
        "Eagles": 24,
        "Steelers": 25,
        "49ers": 28,
        "Seahawks": 29,
        "Buccaneers": 30,
        "Titans": 31,
        "Redskins": 32}

teams_fo = {"NE": "Patriots", 
        "DEN": "Broncos",
        "GB": "Packers",
        "SEA": "Seahawks",
        "SF": "49ers",
        "WAS": "Redskins",
        "NYG": "Giants",
        "DET": "Lions",
        "NO": "Saints",
        "CAR": "Panthers",
        "DAL": "Cowboys",
        "ATL": "Falcons",
        "BAL": "Ravens",
        "TB": "Buccaneers",
        "MIN": "Vikings",
        "HOU": "Texans",
        "CIN": "Bengals",
        "IND": "Colts",
        "PIT": "Steelers",
        "BUF": "Bills",
        "STL": "Rams",
        "MIA": "Dolphins",
        "OAK": "Raiders",
        "SD": "Chargers",
        "PHI": "Eagles",
        "CHI": "Bears",
        "CLE": "Browns",
        "JAC": "Jaguars",
        "TEN": "Titans",
        "NYJ": "Jets",
        "KC": "Chiefs",
        "ARI": "Cardinals"
        }
print(len(teams_fo))

print(sum([x in team_ids_one_on_one.keys() for x in teams_fo.values()]))

def get_team_features(train_year):
   fname = "fo_off_"+str(train_year % 20)+".html"
   with open(fname, "rb") as infile:
       pass
